spring.application.name=student-library-management-system

server.port=1511

#database properties/configurations for connecting mysql database
spring.datasource.url=jdbc:mysql://localhost:3306/student_library_management_system
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#this will show the SQL queries running internally in the console
spring.jpa.show-sql=true

#for automatically update the database after every change
spring.jpa.hibernate.ddl-auto=update

#it converts the java data types into database data type
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect